on:
  push:
    branches:
      - master

# Note: this doesn't work because of auth issues, but I'm leaving it in case
# I ever get motivated to fix it.
jobs:
  publish:
    name: "Publish package"
    strategy:
      matrix:
        package:
          - eslint-config
          - tsconfig
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 18
      - uses: JS-DevTools/npm-publish@v1
        with:
          package: ./packages/${{ matrix.package }}/package.json
          token: ${{ secrets.NPM_AUTH_TOKEN }}
